// frontend/angular-operations/src/app/features/orders/pages/approval-queue-page/approval-queue-page.component.ts
import { DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { finalize } from 'rxjs';
import { EmptyStateComponent } from '../../../../shared/components/empty-state.component';
import { LoadingPanelComponent } from '../../../../shared/components/loading-panel.component';
import { PageHeaderComponent } from '../../../../shared/components/page-header.component';
import { PaginationComponent } from '../../../../shared/components/pagination.component';
import {
  StatusBadgeComponent,
  type StatusBadgeTone,
} from '../../../../shared/components/status-badge.component';
import {
  ApprovalActionType,
  ApprovalRequestStatus,
  ApprovalType,
  type ApprovalRequest,
} from '../../models/orders.model';
import { OrdersApiService } from '../../services/orders-api.service';

@Component({
  selector: 'app-approval-queue-page',
  standalone: true,
  imports: [
    DatePipe,
    FormsModule,
    EmptyStateComponent,
    LoadingPanelComponent,
    PageHeaderComponent,
    PaginationComponent,
    StatusBadgeComponent,
  ],
  templateUrl: './approval-queue-page.component.html',
  styleUrl: './approval-queue-page.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ApprovalQueuePageComponent {
  private readonly api = inject(OrdersApiService);
  protected readonly rows = signal<readonly ApprovalRequest[]>([]);
  protected readonly selected = signal<ApprovalRequest | null>(null);
  protected readonly loading = signal(false);
  protected readonly error = signal('');
  protected readonly success = signal('');
  protected readonly totalCount = signal(0);
  protected readonly totalPages = signal(0);
  protected search = '';
  protected pageNumber = 1;
  protected readonly pageSize = 10;
  protected note = '';
  protected delegateToUserID: number | null = null;
  constructor() {
    this.load();
  }
  protected load(page = this.pageNumber): void {
    this.pageNumber = page;
    this.loading.set(true);
    this.api
      .getApprovalQueue({
        pageNumber: page,
        pageSize: this.pageSize,
        search: this.search,
        sortBy: 'RequestedAt',
        sortDirection: 'desc',
      })
      .pipe(finalize(() => this.loading.set(false)))
      .subscribe({
        next: (r) => {
          this.rows.set(r.items);
          this.totalCount.set(r.totalCount);
          this.totalPages.set(r.totalPages);
        },
        error: () => this.error.set('Unable to load the approval queue.'),
      });
  }
  protected open(id: number): void {
    this.api
      .getApproval(id)
      .subscribe({
        next: (x) => this.selected.set(x),
        error: () => this.error.set('Unable to load approval details.'),
      });
  }
  protected act(action: ApprovalActionType): void {
    const item = this.selected();
    if (!item) return;
    this.api
      .actOnApproval(item.approvalRequestID, {
        action,
        note: this.note.trim() || null,
        delegateToUserID: action === ApprovalActionType.Delegated ? this.delegateToUserID : null,
      })
      .subscribe({
        next: () => {
          this.success.set('Approval action recorded.');
          this.open(item.approvalRequestID);
          this.load();
        },
        error: () => this.error.set('Unable to record the approval action.'),
      });
  }
  protected cancel(): void {
    const item = this.selected();
    if (!item) return;
    this.api.cancelApproval(item.approvalRequestID, this.note.trim() || null).subscribe({
      next: () => {
        this.success.set('Approval request cancelled.');
        this.open(item.approvalRequestID);
        this.load();
      },
      error: () => this.error.set('Unable to cancel the approval request.'),
    });
  }
  protected statusLabel(v: ApprovalRequestStatus): string {
    return ApprovalRequestStatus[v] ?? 'Unknown';
  }
  protected typeLabel(v: ApprovalType): string {
    return ApprovalType[v] ?? 'Unknown';
  }
  protected actionLabel(v: ApprovalActionType): string {
    return ApprovalActionType[v] ?? 'Unknown';
  }
  protected tone(v: ApprovalRequestStatus): StatusBadgeTone {
    if (v === 3) return 'success';
    if (v === 4 || v === 5) return 'danger';
    if (v === 2) return 'warning';
    return 'neutral';
  }
}

<app-page-header
  eyebrow="Approvals"
  title="Approval queue"
  subtitle="Review order, credit, discount, return, inventory, and procurement approval requests."
/>
@if (error()) {
  <div class="alert error">{{ error() }}</div>
}
@if (success()) {
  <div class="alert success">{{ success() }}</div>
}
<section class="section-card">
  <div class="filters">
    <input
      [(ngModel)]="search"
      placeholder="Search by reference type or ID"
      (keyup.enter)="load(1)"
    /><button type="button" (click)="load(1)">Search</button>
  </div>
  @if (loading()) {
    <app-loading-panel message="Loading approval queue..." />
  } @else if (!rows().length) {
    <app-empty-state title="No approval requests found" />
  } @else {
    <div class="table-wrap">
      <table>
        <thead>
          <tr>
            <th>Request</th>
            <th>Reference</th>
            <th>Type</th>
            <th>Requested</th>
            <th>Step</th>
            <th>Status</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          @for (item of rows(); track item.approvalRequestID) {
            <tr>
              <td>#{{ item.approvalRequestID }}</td>
              <td>{{ item.referenceType }} #{{ item.referenceID }}</td>
              <td>{{ typeLabel(item.approvalType) }}</td>
              <td>{{ item.requestedAt | date: 'medium' }}</td>
              <td>{{ item.currentStepNo }}</td>
              <td>
                <app-status-badge [label]="statusLabel(item.status)" [tone]="tone(item.status)" />
              </td>
              <td>
                <button type="button" class="link" (click)="open(item.approvalRequestID)">
                  Open
                </button>
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
    <app-pagination
      [pageNumber]="pageNumber"
      [pageSize]="pageSize"
      [totalCount]="totalCount()"
      [totalPages]="totalPages()"
      (pageChange)="load($event)"
    />
  }
</section>
@if (selected(); as item) {
  <section class="section-card">
    <div class="section-heading">
      <div>
        <h2>Approval request #{{ item.approvalRequestID }}</h2>
        <p>
          {{ item.referenceType }} #{{ item.referenceID }} · Policy #{{ item.approvalPolicyID }}
        </p>
      </div>
      <app-status-badge [label]="statusLabel(item.status)" [tone]="tone(item.status)" />
    </div>
    <div class="table-wrap">
      <table>
        <thead>
          <tr>
            <th>Step</th>
            <th>Action</th>
            <th>By</th>
            <th>At</th>
            <th>Note</th>
          </tr>
        </thead>
        <tbody>
          @for (action of item.actions; track action.approvalActionID) {
            <tr>
              <td>{{ action.stepNo }}</td>
              <td>{{ actionLabel(action.action) }}</td>
              <td>{{ action.actionByName }}</td>
              <td>{{ action.actionAt | date: 'medium' }}</td>
              <td>{{ action.note || '—' }}</td>
            </tr>
          } @empty {
            <tr>
              <td colspan="5" class="empty-row">No action history.</td>
            </tr>
          }
        </tbody>
      </table>
    </div>
    <div class="form-grid">
      <div class="form-field form-field--full">
        <label>Action note</label><textarea rows="3" [(ngModel)]="note"></textarea>
      </div>
      <div class="form-field">
        <label>Delegate to user ID</label><input type="number" [(ngModel)]="delegateToUserID" />
      </div>
    </div>
    @if (item.status === 1 || item.status === 2) {
      <div class="actions">
        <button type="button" (click)="act(2)">Approve</button
        ><button type="button" class="danger" (click)="act(3)">Reject</button
        ><button type="button" class="secondary" (click)="act(6)">Comment</button
        ><button type="button" class="warning" (click)="act(5)">Delegate</button
        ><button type="button" class="danger" (click)="cancel()">Cancel request</button>
      </div>
    }
  </section>
}

// frontend/react-management/src/pages/ApprovalQueuePage.tsx
﻿import {
  type SyntheticEvent,
  useCallback,
  useEffect,
  useMemo,
  useState,
} from "react";

import {
  getApprovalQueue,
  getApprovalRequest,
  recordApprovalAction,
} from "../api/approvalApi";
import { getApiErrorMessage } from "../api/httpClient";
import ApprovalActionDialog from "../components/ApprovalActionDialog";
import DataTable, { type DataTableColumn } from "../components/DataTable";
import ErrorPanel from "../components/ErrorPanel";
import StatusBadge from "../components/StatusBadge";
import { useApi } from "../hooks/useApi";
import { usePermissions } from "../hooks/usePermissions";
import {
  createEmptyPagedResult,
  type PagedResult,
  type StatusTone,
} from "../types/common.types";
import type {
  ApprovalActionRequest,
  ApprovalActionType,
  ApprovalRequest,
  ApprovalRequestStatus,
} from "../types/approval.types";
import { formatDateTime, humanizeCode } from "../utils/formatters";

const PAGE_SIZE = 20;

const statusLabels: Readonly<Record<ApprovalRequestStatus, string>> = {
  1: "Pending",
  2: "In progress",
  3: "Approved",
  4: "Rejected",
  5: "Cancelled",
};

const statusTones: Readonly<Record<ApprovalRequestStatus, StatusTone>> = {
  1: "warning",
  2: "info",
  3: "success",
  4: "danger",
  5: "neutral",
};

const actionLabels: Readonly<Record<ApprovalActionType, string>> = {
  1: "Submitted",
  2: "Approved",
  3: "Rejected",
  4: "Cancelled",
  5: "Delegated",
  6: "Commented",
};

export default function ApprovalQueuePage() {
  const { hasPermission } = usePermissions();

  const canAct = hasPermission("infrastructure.approvals.act");

  const queue = useApi<PagedResult<ApprovalRequest>>(
    createEmptyPagedResult(PAGE_SIZE),
  );

  const details = useApi<ApprovalRequest>();

  const {
    data: queueData,
    isLoading: queueLoading,
    errorMessage: queueErrorMessage,
    execute: executeQueue,
  } = queue;

  const {
    data: activeRequest,
    execute: executeDetails,
    setData: setDetailsData,
  } = details;

  const [pageNumber, setPageNumber] = useState(1);
  const [search, setSearch] = useState("");
  const [appliedSearch, setAppliedSearch] = useState("");

  const [dialogAction, setDialogAction] = useState<Extract<
    ApprovalActionType,
    2 | 3 | 6
  > | null>(null);

  const [actionBusy, setActionBusy] = useState(false);
  const [actionError, setActionError] = useState("");

  const loadQueue = useCallback(
    () =>
      executeQueue(() =>
        getApprovalQueue({
          pageNumber,
          pageSize: PAGE_SIZE,
          search: appliedSearch || undefined,
          sortBy: "requestedAt",
          sortDescending: true,
        }),
      ),
    [appliedSearch, pageNumber, executeQueue],
  );

  useEffect(() => {
    void loadQueue();
  }, [loadQueue]);

  const openDetails = useCallback(
    async (request: ApprovalRequest): Promise<void> => {
      await executeDetails(() => getApprovalRequest(request.approvalRequestID));
    },
    [executeDetails],
  );

  const submitSearch = (event: SyntheticEvent<HTMLFormElement>): void => {
    event.preventDefault();

    setPageNumber(1);
    setAppliedSearch(search.trim());
  };

  const submitAction = async (
    payload: ApprovalActionRequest,
  ): Promise<void> => {
    if (!activeRequest) {
      return;
    }

    const currentRequest = activeRequest;

    setActionBusy(true);
    setActionError("");

    try {
      await recordApprovalAction(currentRequest.approvalRequestID, payload);

      setDialogAction(null);

      await Promise.all([loadQueue(), openDetails(currentRequest)]);
    } catch (error: unknown) {
      setActionError(getApiErrorMessage(error));
    } finally {
      setActionBusy(false);
    }
  };

  const columns = useMemo<readonly DataTableColumn<ApprovalRequest>[]>(
    () => [
      {
        key: "request",
        header: "Request",
        render: (row) => (
          <div className="table-primary">
            <strong>#{row.approvalRequestID}</strong>

            <span>{humanizeCode(row.referenceType)}</span>
          </div>
        ),
      },
      {
        key: "reference",
        header: "Reference",
        render: (row) => `#${row.referenceID}`,
      },
      {
        key: "step",
        header: "Current step",
        render: (row) => row.currentStepNo,
      },
      {
        key: "requested",
        header: "Requested",
        render: (row) => formatDateTime(row.requestedAt),
      },
      {
        key: "status",
        header: "Status",
        render: (row) => (
          <StatusBadge
            label={statusLabels[row.status]}
            tone={statusTones[row.status]}
          />
        ),
      },
      {
        key: "open",
        header: "",
        render: () => <span className="table-link">View details</span>,
      },
    ],
    [],
  );

  const result =
    queueData ?? createEmptyPagedResult<ApprovalRequest>(PAGE_SIZE);

  const canReceiveAction =
    activeRequest?.status === 1 || activeRequest?.status === 2;

  return (
    <main className="management-page">
      <header className="page-heading page-heading--actions">
        <div>
          <p className="page-heading__eyebrow">Management actions</p>

          <h1>Approval Queue</h1>

          <p>
            Review active requests, inspect action history, and record
            management decisions.
          </p>
        </div>

        <form className="search-form" onSubmit={submitSearch}>
          <input
            type="search"
            value={search}
            onChange={(event) => setSearch(event.target.value)}
            placeholder="Search reference type"
            aria-label="Search approval queue"
          />

          <button type="submit" className="msx-button msx-button--primary">
            Search
          </button>
        </form>
      </header>

      {queueErrorMessage ? (
        <ErrorPanel
          message={queueErrorMessage}
          onRetry={() => {
            void loadQueue();
          }}
        />
      ) : null}

      <section className="table-card">
        <DataTable
          rows={result.items}
          columns={columns}
          keyExtractor={(row) => row.approvalRequestID}
          loading={queueLoading}
          onRowClick={(row) => {
            void openDetails(row);
          }}
          emptyMessage="No approval requests match the current search."
        />

        <footer className="pagination-bar">
          <span>
            Page {result.pageNumber || 1} of {Math.max(result.totalPages, 1)} ·{" "}
            {result.totalCount} records
          </span>

          <div>
            <button
              type="button"
              className="msx-button msx-button--ghost"
              disabled={pageNumber <= 1 || queueLoading}
              onClick={() => setPageNumber((value) => Math.max(1, value - 1))}
            >
              Previous
            </button>

            <button
              type="button"
              className="msx-button msx-button--ghost"
              disabled={pageNumber >= result.totalPages || queueLoading}
              onClick={() => setPageNumber((value) => value + 1)}
            >
              Next
            </button>
          </div>
        </footer>
      </section>

      {activeRequest ? (
        <aside className="details-panel" aria-label="Approval request details">
          <header className="details-panel__header">
            <div>
              <p>
                {humanizeCode(activeRequest.referenceType)} #
                {activeRequest.referenceID}
              </p>

              <h2>Approval request #{activeRequest.approvalRequestID}</h2>
            </div>

            <button
              type="button"
              className="icon-button"
              aria-label="Close details"
              onClick={() => setDetailsData(null)}
            >
              ×
            </button>
          </header>

          <dl className="details-grid">
            <div>
              <dt>Status</dt>

              <dd>
                <StatusBadge
                  label={statusLabels[activeRequest.status]}
                  tone={statusTones[activeRequest.status]}
                />
              </dd>
            </div>

            <div>
              <dt>Current step</dt>

              <dd>{activeRequest.currentStepNo}</dd>
            </div>

            <div>
              <dt>Requested by user</dt>

              <dd>#{activeRequest.requestedByUserID}</dd>
            </div>

            <div>
              <dt>Requested at</dt>

              <dd>{formatDateTime(activeRequest.requestedAt)}</dd>
            </div>
          </dl>

          <section className="timeline">
            <h3>Action history</h3>

            {activeRequest.actions.length === 0 ? (
              <p>No actions have been recorded.</p>
            ) : (
              activeRequest.actions.map((action) => (
                <article key={action.approvalActionID}>
                  <span className="timeline__dot" aria-hidden="true" />

                  <div>
                    <strong>{actionLabels[action.action]}</strong>

                    <span>
                      {action.actionByName} · {formatDateTime(action.actionAt)}
                    </span>

                    {action.note ? <p>{action.note}</p> : null}
                  </div>
                </article>
              ))
            )}
          </section>

          {canAct && canReceiveAction ? (
            <div className="details-panel__actions">
              <button
                type="button"
                className="msx-button msx-button--secondary"
                onClick={() => {
                  setActionError("");
                  setDialogAction(6);
                }}
              >
                Comment
              </button>

              <button
                type="button"
                className="msx-button msx-button--danger"
                onClick={() => {
                  setActionError("");
                  setDialogAction(3);
                }}
              >
                Reject
              </button>

              <button
                type="button"
                className="msx-button msx-button--primary"
                onClick={() => {
                  setActionError("");
                  setDialogAction(2);
                }}
              >
                Approve
              </button>
            </div>
          ) : null}
        </aside>
      ) : null}

      <ApprovalActionDialog
        request={activeRequest}
        action={dialogAction}
        busy={actionBusy}
        errorMessage={actionError}
        onClose={() => {
          setActionError("");
          setDialogAction(null);
        }}
        onSubmit={submitAction}
      />
    </main>
  );
}
