// frontend/react-management/src/components/LoadingPanel.tsx
﻿export interface LoadingPanelProps {
  message?: string;
  compact?: boolean;
  overlay?: boolean;
}

export default function LoadingPanel({
  message = "Loading...",
  compact = false,
  overlay = false,
}: LoadingPanelProps) {
  const className = [
    "loading-panel",
    compact ? "loading-panel--compact" : "",
    overlay ? "loading-panel--overlay" : "",
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <div
      className={className}
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <span className="loading-panel__spinner" aria-hidden="true" />
      <span className="loading-panel__message">{message}</span>
    </div>
  );
}

// frontend/angular-operations/src/app/shared/components/loading-panel.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

@Component({
  selector: 'app-loading-panel',
  standalone: true,
  templateUrl: './loading-panel.component.html',
  styleUrl: './loading-panel.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LoadingPanelComponent {
  @Input() message = 'Loading...';
  @Input() compact = false;
  @Input() overlay = false;
}

<div
  class="loading-panel"
  [class.loading-panel--compact]="compact"
  [class.loading-panel--overlay]="overlay"
  role="status"
  aria-live="polite"
  aria-busy="true"
>
  <span class="loading-panel__spinner" aria-hidden="true"></span>
  <span class="loading-panel__message">{{ message }}</span>
</div>
