// frontend/react-management/src/components/StatusBadge.tsx
﻿import type { StatusTone } from "../types/common.types";

export interface StatusBadgeProps {
  label: string;
  tone?: StatusTone;
  showDot?: boolean;
}

export default function StatusBadge({
  label,
  tone = "neutral",
  showDot = true,
}: StatusBadgeProps) {
  return (
    <span className={`status-badge status-badge--${tone}`}>
      {showDot ? (
        <span className="status-badge__dot" aria-hidden="true" />
      ) : null}
      <span>{label}</span>
    </span>
  );
}

// frontend/angular-operations/src/app/shared/components/status-badge.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

export type StatusBadgeTone = 'neutral' | 'info' | 'success' | 'warning' | 'danger';

@Component({
  selector: 'app-status-badge',
  standalone: true,
  templateUrl: './status-badge.component.html',
  styleUrl: './status-badge.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class StatusBadgeComponent {
  @Input() label = '';
  @Input() tone: StatusBadgeTone = 'neutral';
  @Input() showDot = true;
}

<span class="status-badge" [class]="'status-badge status-badge--' + tone">
  @if (showDot) {
    <span class="status-badge__dot" aria-hidden="true"></span>
  }
  <span>{{ label }}</span>
</span>
