// frontend/react-management/src/pages/LoginPage.tsx
﻿import { type SyntheticEvent, useEffect, useState } from "react";
import { Navigate, useLocation, useNavigate } from "react-router-dom";

import { getApiErrorMessage } from "../api/httpClient";
import { useAuth } from "../auth/useAuth";

interface LocationState {
  from?:
    | string
    | {
        pathname?: string;
        search?: string;
      };

  passwordChanged?: boolean;
}

const validManagementRoutes = new Set([
  "/",
  "/dashboard",
  "/lead-to-order-funnel",
  "/campaign-roi",
  "/gt-vs-mt-sales",
  "/sell-in-sell-out",
  "/inventory-health",
  "/delivery-return",
  "/employee-kpi",
  "/client-360",
  "/approvals",
  "/access-denied",
]);

function resolveRequestedPath(state: LocationState | null): string {
  let requestedPath = "/dashboard";

  if (typeof state?.from === "string") {
    requestedPath = state.from;
  } else if (state?.from) {
    requestedPath = `${state.from.pathname || ""}${state.from.search || ""}`;
  }

  if (!requestedPath) {
    return "/dashboard";
  }

  const pathname = requestedPath.split("?")[0] || "/dashboard";

  if (!validManagementRoutes.has(pathname)) {
    return "/dashboard";
  }

  return pathname === "/" ? "/dashboard" : requestedPath;
}

export default function LoginPage() {
  const navigate = useNavigate();
  const location = useLocation();

  const { currentUser, isAuthenticated, isInitializing, login } = useAuth();

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");

  const state = location.state as LocationState | null;

  const requestedPath = resolveRequestedPath(state);

  useEffect(() => {
    document.title = "Sign In | MarketSphere ConvertX";
  }, []);

  if (!isInitializing && isAuthenticated && currentUser?.mustChangePassword) {
    return (
      <Navigate
        to="/change-password"
        replace
        state={{
          from: requestedPath,
        }}
      />
    );
  }

  if (!isInitializing && isAuthenticated && !currentUser?.mustChangePassword) {
    return <Navigate to={requestedPath} replace />;
  }

  async function handleSubmit(
    event: SyntheticEvent<HTMLFormElement>,
  ): Promise<void> {
    event.preventDefault();
    setErrorMessage("");

    if (!email.trim() || !password) {
      setErrorMessage("Email address and password are required.");

      return;
    }

    setIsSubmitting(true);

    try {
      const session = await login({
        email: email.trim(),
        password,
      });

      if (session.user.mustChangePassword) {
        navigate("/change-password", {
          replace: true,
          state: {
            from: requestedPath,
          },
        });

        return;
      }

      navigate(requestedPath, {
        replace: true,
      });
    } catch (error: unknown) {
      setErrorMessage(
        getApiErrorMessage(
          error,
          "Login failed. Check your email and password.",
        ),
      );
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <div className="auth-page">
      <div className="auth-page__visual" aria-hidden="true">
        <div className="auth-page__visual-content">
          <span className="auth-page__brand-mark">M</span>

          <p className="auth-page__eyebrow">MarketSphere ConvertX</p>

          <h1>Management insight with controlled access.</h1>

          <p>
            Sign in to review analytics, approvals, KPI performance, and
            business drill-down reports.
          </p>
        </div>
      </div>

      <main className="auth-page__content">
        <section className="auth-card" aria-labelledby="login-title">
          <div className="auth-card__heading">
            <span className="auth-card__mobile-brand">
              MarketSphere ConvertX
            </span>

            <h2 id="login-title">Management sign in</h2>

            <p>Use your approved MarketSphere account.</p>
          </div>

          {state?.passwordChanged ? (
            <div className="auth-alert auth-alert--success" role="status">
              Password changed successfully. Sign in again using your new
              password.
            </div>
          ) : null}

          {errorMessage ? (
            <div className="auth-alert auth-alert--danger" role="alert">
              {errorMessage}
            </div>
          ) : null}

          <form className="auth-form" onSubmit={handleSubmit} noValidate>
            <label className="msx-field">
              <span className="msx-label">Email address</span>

              <input
                autoFocus
                className="msx-input"
                type="email"
                value={email}
                onChange={(event) => setEmail(event.target.value)}
                autoComplete="username"
                placeholder="name@company.com"
                maxLength={256}
              />
            </label>

            <label className="msx-field">
              <span className="msx-label">Password</span>

              <span className="auth-password-field">
                <input
                  className="msx-input"
                  type={showPassword ? "text" : "password"}
                  value={password}
                  onChange={(event) => setPassword(event.target.value)}
                  autoComplete="current-password"
                  placeholder="Enter your password"
                  maxLength={200}
                />

                <button
                  type="button"
                  className="auth-password-field__toggle"
                  onClick={() => setShowPassword((value) => !value)}
                  aria-label={showPassword ? "Hide password" : "Show password"}
                >
                  {showPassword ? "Hide" : "Show"}
                </button>
              </span>
            </label>

            <button
              type="submit"
              className="msx-button msx-button--primary auth-form__submit"
              disabled={isSubmitting}
            >
              {isSubmitting ? "Signing in..." : "Sign in"}
            </button>
          </form>

          <p className="auth-card__support">
            User accounts and permissions are controlled in the Angular
            Operations Portal.
          </p>
        </section>
      </main>
    </div>
  );
}

// frontend/angular-operations/src/app/features/auth/pages/login-page/login-page.component.ts
﻿import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { finalize } from 'rxjs';

import { AuthService } from '../../../../core/auth/auth.service';
import { getApiErrorMessage } from '../../../../core/http/error.interceptor';
import { AutofocusDirective } from '../../../../shared/directives/autofocus.directive';

const FIELD_ROLE_CODES = [
  'SALES_OFFICER',
  'MT_EXECUTIVE',
  'BUSINESS_PROMOTER',
  'MERCHANDISER',
] as const;

@Component({
  selector: 'app-login-page',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, AutofocusDirective],
  templateUrl: './login-page.component.html',
  styleUrl: './login-page.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LoginPageComponent {
  private readonly formBuilder = inject(FormBuilder);
  private readonly authService = inject(AuthService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly destroyRef = inject(DestroyRef);

  protected readonly isSubmitting = signal(false);
  protected readonly errorMessage = signal('');
  protected readonly showPassword = signal(false);

  protected readonly form = this.formBuilder.nonNullable.group({
    email: ['', [Validators.required, Validators.email, Validators.maxLength(256)]],
    password: ['', [Validators.required, Validators.maxLength(200)]],
  });

  protected get sessionExpired(): boolean {
    return this.route.snapshot.queryParamMap.get('sessionExpired') === 'true';
  }

  protected togglePasswordVisibility(): void {
    this.showPassword.update((value) => !value);
  }

  protected submit(): void {
    this.errorMessage.set('');
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.isSubmitting.set(true);
    this.authService
      .login(this.form.getRawValue())
      .pipe(
        finalize(() => this.isSubmitting.set(false)),
        takeUntilDestroyed(this.destroyRef),
      )
      .subscribe({
        next: (session) => {
          const safeReturnUrl = this.getSafeReturnUrl();
          const isFieldUser = FIELD_ROLE_CODES.some((role) =>
            session.user.roleCodes.includes(role),
          );
          const target = session.user.mustChangePassword
            ? '/auth/change-password'
            : safeReturnUrl || (isFieldUser ? '/field/home' : '/dashboard');
          void this.router.navigateByUrl(target);
        },
        error: (error: unknown) => {
          this.errorMessage.set(
            getApiErrorMessage(error, 'Login failed. Check your email and password.'),
          );
        },
      });
  }

  private getSafeReturnUrl(): string | null {
    const returnUrl = this.route.snapshot.queryParamMap.get('returnUrl');
    if (!returnUrl || !returnUrl.startsWith('/') || returnUrl.startsWith('//')) return null;
    if (returnUrl.startsWith('/auth/login')) return null;
    return returnUrl;
  }
}


<div class="auth-page">
  <div class="auth-page__visual" aria-hidden="true">
    <div class="auth-page__visual-content">
      <span class="auth-page__brand-mark">M</span>
      <p class="auth-page__eyebrow">MarketSphere ConvertX</p>
      <h1>One platform for complete business operations.</h1>
      <p>
        Sign in to access the Angular operations portal with your assigned roles and permissions.
      </p>
    </div>
  </div>

  <main class="auth-page__content">
    <section class="auth-card" aria-labelledby="login-title">
      <div class="auth-card__heading">
        <span class="auth-card__mobile-brand">MarketSphere ConvertX</span>
        <h2 id="login-title">Welcome back</h2>
        <p>Enter your credentials to continue.</p>
      </div>

      @if (sessionExpired) {
        <div class="auth-alert auth-alert--warning" role="status">
          Your session expired. Sign in again to continue.
        </div>
      }

      @if (errorMessage()) {
        <div class="auth-alert auth-alert--danger" role="alert">
          {{ errorMessage() }}
        </div>
      }

      <form class="auth-form" [formGroup]="form" (ngSubmit)="submit()" novalidate>
        <label class="msx-field">
          <span class="msx-label">Email address</span>
          <input
            appAutofocus
            class="msx-input"
            type="email"
            formControlName="email"
            autocomplete="username"
            placeholder="name@company.com"
            [attr.aria-invalid]="form.controls.email.invalid && form.controls.email.touched"
          />

          @if (form.controls.email.touched && form.controls.email.hasError('required')) {
            <span class="msx-field-error">Email address is required.</span>
          } @else if (form.controls.email.touched && form.controls.email.hasError('email')) {
            <span class="msx-field-error">Enter a valid email address.</span>
          }
        </label>

        <label class="msx-field">
          <span class="msx-label">Password</span>
          <span class="auth-password-field">
            <input
              class="msx-input"
              [type]="showPassword() ? 'text' : 'password'"
              formControlName="password"
              autocomplete="current-password"
              placeholder="Enter your password"
              [attr.aria-invalid]="form.controls.password.invalid && form.controls.password.touched"
            />
            <button
              type="button"
              class="auth-password-field__toggle"
              (click)="togglePasswordVisibility()"
              [attr.aria-label]="showPassword() ? 'Hide password' : 'Show password'"
            >
              {{ showPassword() ? 'Hide' : 'Show' }}
            </button>
          </span>

          @if (form.controls.password.touched && form.controls.password.hasError('required')) {
            <span class="msx-field-error">Password is required.</span>
          }
        </label>

        <button
          type="submit"
          class="msx-button msx-button--primary auth-form__submit"
          [disabled]="isSubmitting()"
        >
          {{ isSubmitting() ? 'Signing in...' : 'Sign in' }}
        </button>
      </form>

      <p class="auth-card__support">
        Account activation and password reset are controlled by your system administrator.
      </p>
    </section>
  </main>
</div>
