// frontend/angular-operations/src/app/shared/components/empty-state.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

export type EmptyStateIcon = 'inbox' | 'search' | 'warning' | 'offline';

@Component({
  selector: 'app-empty-state',
  standalone: true,
  templateUrl: './empty-state.component.html',
  styleUrl: './empty-state.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class EmptyStateComponent {
  @Input() title = 'No data found';
  @Input() message = 'There is no information to display yet.';
  @Input() actionLabel = '';
  @Input() icon: EmptyStateIcon = 'inbox';
  @Input() compact = false;

  @Output() readonly actionRequested = new EventEmitter<void>();

  protected requestAction(): void {
    this.actionRequested.emit();
  }
}

<section class="empty-state" [class.empty-state--compact]="compact">
  <div class="empty-state__icon" aria-hidden="true">
    @switch (icon) {
      @case ('search') {
        <span>⌕</span>
      }
      @case ('warning') {
        <span>!</span>
      }
      @case ('offline') {
        <span>↯</span>
      }
      @default {
        <span>□</span>
      }
    }
  </div>

  <h3>{{ title }}</h3>
  <p>{{ message }}</p>

  @if (actionLabel) {
    <button type="button" class="msx-button msx-button--primary" (click)="requestAction()">
      {{ actionLabel }}
    </button>
  }
</section>

// frontend/react-management/src/components/EmptyState.tsx
﻿export type EmptyStateIcon = "inbox" | "search" | "warning" | "offline";

export interface EmptyStateProps {
  title?: string;
  message?: string;
  actionLabel?: string;
  icon?: EmptyStateIcon;
  compact?: boolean;
  onAction?: () => void;
}

const iconText: Readonly<Record<EmptyStateIcon, string>> = {
  inbox: "□",
  search: "⌕",
  warning: "!",
  offline: "↯",
};

export default function EmptyState({
  title = "No data found",
  message = "There is no information to display yet.",
  actionLabel,
  icon = "inbox",
  compact = false,
  onAction,
}: EmptyStateProps) {
  return (
    <section className={`empty-state${compact ? " empty-state--compact" : ""}`}>
      <div className="empty-state__icon" aria-hidden="true">
        {iconText[icon]}
      </div>

      <h3>{title}</h3>
      <p>{message}</p>

      {actionLabel && onAction ? (
        <button
          type="button"
          className="msx-button msx-button--primary"
          onClick={onAction}
        >
          {actionLabel}
        </button>
      ) : null}
    </section>
  );
}
